config/routes.rb
Rails.application.routes.draw do
  resources :body_types
  resources :bodies

  root 'body_types#index'
  

end

app/models/body.rb
class Body < ActiveRecord::Base
  belongs_to :body_type  # related to only one body type, so not plural

  def diameter_in_kms
    relative_diameter * 12742
  end
  
end

app/models/body_type.rb
class BodyType < ActiveRecord::Base
   has_many :bodies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_body_type

	def current_body_type
		if session.key?(:body_type_id)
			BodyType.find(session[:body_type_id])
		else
			nil
		end
	end
end

app/controllers/background_controller.rb
class BackgroundController < ApplicationController
end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController
  def show
    @body = Body.find(params[:id])
  end
end

app/controllers/body_types_controller.rb
class BodyTypesController < ApplicationController
  def index
    @body_types = BodyType.order('name ASC') #name sorted 'Ascending'
  end

  def show
    @body_type = BodyType.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/background_helper.rb
module BackgroundHelper

 def body_style
      "background-image: url(" + asset_path('bg-stars.png') + ")"
  end

end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/helpers/body_types_helper.rb
module BodyTypesHelper
end

app/views/bodies/show.html.erb
<div class="row">
  <div id="leftCol" class="col-xs-3">
    <h1><%= @body.name %></h1>

    <h4>This is a <%= @body.body_type.name %></h4>

    <h4>It is the <%= (@body.position_from_sun).ordinalize %> rock from the sun.</h4>

    <h4>Diameter: <%= (@body.diameter_in_kms).round(4) %> kms</h4>

    <p>Back Link: <%= link_to(@body.body_type.name, body_type_path(@body.body_type)) %></p>
    
  </div>
  <div id="rightcol" class="col-xs-9">
   
      <iframe src="http://codepen.io/juliangarnier/full/idhuG" width="100%" height="600px" frameborder="0"></iframe>
  </div>
</div>

app/views/body_types/_body_types.html.erb
<p><%= link_to 'Add a new one', new_item_type_item_path(item_type) %></p>
  <% body_type.bodies.each do |body| %>
    <%= render body %>
    <p><%= link_to item.title, item_type_item_path(item_type, item) %></p>
  <% end %>

app/views/body_types/index.html.erb
<div class="row">
  <div id="leftCol" class="col-xs-3">
    <h1>Our Solar System:</h1>

    <p>We have <% @body_types.count %> Body types! </p>

    <p><% @body_types.each do |body_type| %>
    
      <h4><%= link_to(body_type.name, body_type_path(body_type)) %></h4>
    </p>

    <%#= render 'body_types/body_types' %>
    <% end %>

    <p></p>

    <%= render 'layouts/ssControls' %>

  </div>
  <div id="rightcol" class="col-xs-9">
 
   <iframe src="http://codepen.io/juliangarnier/full/idhuG" width="100%" height="600px" frameborder="0"></iframe>
  </div>
</div>

app/views/body_types/show.html.erb
<div class="row">
  <div id="leftCol" class="col-xs-3">
    <h1><%= @body_type.name %></h1>

     <% @body_type.bodies.each do |body| %>

      <h4><%= link_to(body.name, body_path(body)) %></h4>

     <% end %>
     
     
  </div>
  <div id="rightcol" class="col-xs-9">
      
        <iframe src="http://codepen.io/juliangarnier/full/idhuG" width="100%" height="600px" frameborder="0"></iframe>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div>
  <footer class="footer">
    <hr />
    <p><%= link_to 'Home', root_path %></p>
    <hr />
    <small>
    <p>Format and Boostrap stuff from<br/>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a><br />
    Overall Project by <a href="http://mowen.imgd.ca/nextweb/">Mike Owen</a>
    </p>
    </small>
  </footer>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
  <!-- <%= link_to "sample app", '#', id: "logo" %> -->
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'IMG 240', 'http://adunae.imgd.ca/' %></li>
        <li><%= link_to 'NicGuy59', 'http://mowen.imgd.ca/nextweb/' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_item.html.erb
<div class="row">
  <div id="leftCol" class="col-xs-3">
    <h3>What have we got here?</h3>
      <p> We have <% @body_types.count %> Celestial Body types! </p>
      <% @body_types.each do |body_type| %>
        <%= link_to(body_type.name, body_type_path(body_type)) %></p>
      <% end %>
  </div>
  <div id="rightcol" class="col-xs-9">
    <p>Spacer for the solar system graphic</p>
  </div>
</div>
<div class="row">
  <div class="col-xs-12">
    <p></p>
    <hr />
  </div>
</div>

app/views/layouts/_ssControls.html.erb
<div class="ssControls">
<p></p>
<hr />
<h4>3D Solar System Controls</h4>

<p>The 3D Solar System display on the right is a plug-in, and not connected to the Ruby Text App.  It is just for looks.
<p>Click on "Data" to see individual body information<br />
"Data" is found in the top left corner of the solar system display, under the "CSS 3D Solar System" title in the Right Panel Header.</p>
<p>Click on "Controls" to see individual body information<br />
"Controls" is found in the top right corner of the solar system display, under the "Sign Up" button in the Right Panel Header.</p>

</div>
<hr />
<small></small>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
      <title>Solarsystem</title>
      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
      <%= csrf_meta_tags %>
  </head>

  <body>
    <!-- Structure source: "https://www.railstutorial.org/book/filling_in_the_layout" -->
    <%= render 'layouts/header' %>
    <div class="container">
      <!-- Add in background stars.  Needed Background Controller and Helper -->
      <body style="<%= body_style %>">
      <%= yield %>

    </div> 
    <%= render 'layouts/footer' %>    
  </body>
</html>